### ISSUE TITLE
Set Canonical URL to be: gorgonia.org/gorgonia

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#117]
Thoughts?

Then when we split out the tensor package, these will be the packages: 

- [x] gorgonia.org/tensor
    - [x] Vanity URL
    - [x] Canonical URL
- [ ] gorgonia.org/gorgonia
    - [x] Vanity URL
    - [ ] Canonical URL
- [x] gorgonia.org/cu
    - [x] Vanity URL
    - [x] Canonical URL
- [x] gorgonia.org/vecf64
    - [x] Vanity URL
    - [x] Canonical URL
- [x] gorgonia.org/vecf32
    - [x] Vanity URL
    - [x] Canonical URL

This will aid with #98 much better

# TODO #
* [x] Add meta redirect in gorgonia.org ([test link](https://gorgonia.org/gorgonia))
* [ ] Add canonical import path in gorgonia package
