### ISSUE TITLE
Split out execution and data structures for `tensor`

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#128]
`tensor/ops` directory to handle all the operations that are not specific to matop. 

`genlib` will have to generate those specific operations.

The rules are: 

1. Anything that has to do with the tensor object dealing with itself (`matop` stuff essentially) stays in package `tensor`
2. Everything else that uses the tensor data structures (arithmetics, linear algebra etc) is moved out.

# TODO #
- [x] #129 
- [x] Create `tensor/internal/execution`
- [x] Move basic arith ops to `execution`
- [x] Move Dense arith methods to use `Engine`
- [x] Move Dense cmp methods to use `Engine`
- [x] Move data-movement methods to use `Engine`
- [x] Move linalg ops to `Engine`
- [x] Move arg methods to use `Engine`
- [x] Create a `StdEngine` in `tensor` that embeds `"internal/execution".E`
- [x] Generate comprehensive tests

**Comment by chewxy** [comment]
Fixed as of a5f7451
