### ISSUE TITLE
Use negative shape dimensions for dynamic/variable shapes

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#96]
Allow for such shapes: `(-1, 200)`. This allows for shapes that change at run time. 

## Pros ##

The running example used is in the context of generating logical forms coupled with a reinforcement learning algorithm.

In a logical form generator, a seq2seq network (or even just a maximum likelihood model paired with a traditional chart parser) would generate `n` logical forms, which is then scored, and weighted with the rewards. A pseudomodel is something like this:

```go
// elided: a complicated model that generates a rewards vector with dynamic size

weights := 500
w := NewVector(g, Float64, WithShape(weights), WithName("weights"), WithInit(GlorotU(1)))
x := NewMatrix(g, Float64, WithShape(weights, rewards), WithName("xs"))
r := NewVector(g, Float64, WithShape(rewards), WithName("reward weighting"))
a := Must(Tanh(Must(Mul(w, f)))
WithName("activated")(a)
rWeighted := Must(HadamardProd(r, a))
```

Here `rewards` is the size of dynamically sized vector that will change size based on whatever the reinforcement learning algorithm (or a seq2seq network) returns. 

Symbolically, we can work out the shape of `a` to be `(rewards)`. Allowing negative shape dimensions would allow for variable shapes. 

## Cons ##
*  Huge footprint - this change affects many moving parts, especially with allocating the slices.
* Potential performance issues - currently `Value` stored in the `*Node` doesn't change once it's been allocated. Additional values are merely copied into it. If the shape changes, then plenty more allocations and freeing would be required.

## Current Workarounds ##
Currently, a manual update to the shapes are required to each node at each runtime. While in the example above it's very easy (as there are only two `*Nodes` to update), especially with a `LispMachine`, This gets very complicated as a new shape calculator needs to be created with each application.

### Alternative Slutions ###
* Create `AsShape` `Op`s. - this sidesteps all the 

### Handling Negative Shape Dimensions ###
* Treat the negative dimensions as a size hint/signal.
* `TotalSize` is calculated the same way, but with an additional `abs()` called to give a total positive size.

## TODO ##
* [ ] Gather all the places this change would affect
* [x] Propose a mechanism for handling negative shape dimensions.
* [x] Propose alternatives (with pros and cons).
